#!/usr/bin/env bash
# Build the repository-owned TeX image and write tooling/toolchain.lock.json from what the built
# image actually reports — never from what the Dockerfile intended.
#
# Run this whenever tooling/Dockerfile changes. The lock file is committed; a drift between the
# lock file and a freshly built image is a reviewable change, not a silent one.

set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PLATFORM="${1:-linux/arm64}"
TAG="wm-tex:local-${PLATFORM##*/}"

command -v docker >/dev/null 2>&1 || { echo "FATAL: docker required" >&2; exit 2; }

echo "== building $TAG for $PLATFORM"
docker build --platform "$PLATFORM" -t "$TAG" -f "$REPO/tooling/Dockerfile" "$REPO/tooling/"

BASE_DIGEST=$(grep -oE 'sha256:[0-9a-f]{64}' "$REPO/tooling/Dockerfile" | head -1)
VERSIONS=$(docker run --rm --platform "$PLATFORM" "$TAG" cat /toolchain-versions.txt)

get() { echo "$VERSIONS" | grep "^$1=" | cut -d= -f2-; }

python3 - "$REPO" "$TAG" "$PLATFORM" "$BASE_DIGEST" \
         "$(get xelatex)" "$(get latexmk)" "$(get bibtex)" "$(get debian)" "$(get pdftotext)" \
         "$(get tex_live)" <<'PY'
import json, pathlib, sys
repo, tag, platform, base, xelatex, latexmk, bibtex, debian, pdftotext, tex_live = sys.argv[1:11]
lock_path = pathlib.Path(repo) / "tooling/toolchain.lock.json"

lock = {
    "_comment": (
        "Generated by scripts/lock-toolchain.sh from the built image. Do not hand-edit: every "
        "version string here was read out of a running container, not transcribed from intent."
    ),
    "image": {
        "name": "wm-tex",
        "ref_pattern": "wm-tex:local-<arch>",
        "example_ref": tag,
        "built_from": "tooling/Dockerfile",
        "base_image": "debian:bookworm-slim",
        "index_digest": base,
        "platform_digests": {
            "linux/amd64": "SEE base index digest — resolved per platform by the registry",
            "linux/arm64": "SEE base index digest — resolved per platform by the registry",
        },
        "note": (
            "The image is built from a Dockerfile in this repository rather than pulled, so the "
            "pinned identity is the BASE image digest plus the package set in the Dockerfile."
        ),
    },
    "engine": "pdflatex",
    "engine_rationale": (
        "The source is written for pdfTeX: it loads cmap and T1 fontenc, both of which are pdfTeX "
        "constructs and both inert under XeLaTeX. The imported baseline was nonetheless built with "
        "xelatex/xdvipdfmx, which is the measured cause of findings E-01 and H-02. RC001 aligns "
        "the engine to the source. Evidence: publication/WM-1.1-BUILD-ENGINE-DECISION-001.md."
    ),
    "jobname": "WM-1.1-RC002",
    "default_platform": platform,
    "fallback_source_date_epoch": 1785600000,
    "versions": {
        "engine": xelatex,
        "latexmk": latexmk,
        "bib_tool": bibtex,
        "tex_live": tex_live or "UNAVAILABLE",
        "debian_version": debian,
        "pdftotext": pdftotext,
    },
    "fonts": {
        "family": "Latin Modern (lmodern)",
        "encoding": "T1",
        "embedding": "all subsets embedded by the engine; enforced by scripts/qa.py gate F-01",
    },
    "locale": "C.UTF-8",
    "timezone": "UTC",
}
lock_path.write_text(json.dumps(lock, indent=2, ensure_ascii=False) + "\n")
print(f"WROTE   tooling/toolchain.lock.json")
PY

echo "== toolchain versions observed:"
echo "$VERSIONS" | sed 's/^/   /'
